export const areas = {
  //서울
  "01": {
    0: { x: 61, y: 126, isShow: true, name: "강남구" },
    1: { x: 62, y: 126, isShow: true, name: "강동구" },
    2: { x: 61, y: 128, isShow: true, name: "강북구" },
    3: { x: 58, y: 126, isShow: true, name: "강서구" },
    4: { x: 59, y: 125, isShow: true, name: "관악구" },
    5: { x: 62, y: 126, isShow: true, name: "광진구" },
    6: { x: 58, y: 125, isShow: true, name: "구로구" },
    7: { x: 59, y: 124, isShow: true, name: "금천구" },
    8: { x: 61, y: 129, isShow: true, name: "노원구" },
    9: { x: 61, y: 129, isShow: true, name: "도봉구" },
    10: { x: 61, y: 127, isShow: true, name: "동대문구" },
    11: { x: 59, y: 125, isShow: true, name: "동작구" },
    12: { x: 59, y: 127, isShow: true, name: "마포구" },
    13: { x: 59, y: 127, isShow: true, name: "서대문구" },
    14: { x: 61, y: 125, isShow: true, name: "서초구" },
    15: { x: 61, y: 127, isShow: true, name: "성동구" },
    16: { x: 61, y: 127, isShow: true, name: "성북구" },
    17: { x: 62, y: 126, isShow: true, name: "송파구" },
    18: { x: 58, y: 126, isShow: true, name: "양천구" },
    19: { x: 58, y: 126, isShow: true, name: "영등포구" },
    20: { x: 60, y: 126, isShow: true, name: "용산구" },
    21: { x: 60, y: 127, isShow: true, name: "은평구" },
    22: { x: 60, y: 127, isShow: true, name: "종로구" },
    23: { x: 60, y: 127, isShow: true, name: "중구" },
    24: { x: 62, y: 128, isShow: true, name: "중랑구" },
  },
  //부산
  "02": {
    0: { x: 96, y: 76, isShow: true, name: "강서구" },
    1: { x: 96, y: 76, isShow: true, name: "강서구" },
    2: { x: 98, y: 77, isShow: true, name: "금정구" },
    3: { x: 100, y: 77, isShow: true, name: "기장군" },
    4: { x: 98, y: 75, isShow: true, name: "남구" },
    5: { x: 98, y: 75, isShow: true, name: "동구" },
    6: { x: 98, y: 76, isShow: true, name: "동래구" },
    7: { x: 97, y: 75, isShow: true, name: "부산진구" },
    8: { x: 96, y: 76, isShow: true, name: "북구" },
    9: { x: 96, y: 75, isShow: true, name: "사상구" },
    10: { x: 96, y: 74, isShow: true, name: "사하구" },
    11: { x: 97, y: 74, isShow: true, name: "서구" },
    12: { x: 99, y: 75, isShow: true, name: "수영구" },
    13: { x: 98, y: 76, isShow: true, name: "연제구" },
    14: { x: 98, y: 74, isShow: true, name: "영도구" },
    15: { x: 97, y: 74, isShow: true, name: "중구" },
    16: { x: 99, y: 75, isShow: true, name: "해운대구" },
  },
  // 인천
  "03": {
    0: { x: 51, y: 130, isShow: true, name: "강화군" },
    1: { x: 51, y: 130, isShow: true, name: "강화군" },
    2: { x: 51, y: 130, isShow: true, name: "강화군" },
    3: { x: 51, y: 130, isShow: true, name: "강화군" },
    4: { x: 51, y: 130, isShow: true, name: "강화군" },
    5: { x: 51, y: 130, isShow: true, name: "강화군" },
    6: { x: 56, y: 126, isShow: true, name: "계양구" },
    7: { x: 56, y: 124, isShow: true, name: "남동구" },
    8: { x: 54, y: 125, isShow: true, name: "동구" },
    9: { x: 54, y: 124, isShow: true, name: "미추홀구" },
    10: { x: 55, y: 125, isShow: true, name: "부평구" },
    11: { x: 55, y: 126, isShow: true, name: "서구" },
    12: { x: 55, y: 123, isShow: true, name: "연수구" },
    13: { x: 54, y: 124, isShow: true, name: "옹진군" },
    14: { x: 54, y: 124, isShow: true, name: "옹진군" },
    15: { x: 54, y: 124, isShow: true, name: "옹진군" },
    16: { x: 54, y: 124, isShow: true, name: "옹진군" },
    17: { x: 54, y: 125, isShow: true, name: "중구" },
    18: { x: 54, y: 125, isShow: true, name: "중구" },
  },
  // 대구
  "04": {
    0: { x: 89, y: 90, isShow: true, name: "남구" },
    1: { x: 88, y: 90, isShow: true, name: "달서구" },
    2: { x: 86, y: 88, isShow: true, name: "달성군" },
    3: { x: 86, y: 88, isShow: true, name: "달성군" },
    4: { x: 90, y: 91, isShow: true, name: "동구" },
    5: { x: 89, y: 91, isShow: true, name: "북구" },
    6: { x: 88, y: 90, isShow: true, name: "서구" },
    7: { x: 89, y: 90, isShow: true, name: "수성구" },
    8: { x: 89, y: 90, isShow: true, name: "중구" },
  },
  // 대전
  "05": {
    0: { x: 68, y: 100, isShow: true, name: "대덕구" },
    1: { x: 68, y: 100, isShow: true, name: "동구" },
    2: { x: 67, y: 100, isShow: true, name: "서구" },
    3: { x: 67, y: 101, isShow: true, name: "유성구" },
    4: { x: 68, y: 100, isShow: true, name: "중구" },
  },
  // 광주
  "06": {
    0: { x: 57, y: 74, isShow: true, name: "광산구" },
    1: { x: 59, y: 73, isShow: true, name: "남구" },
    2: { x: 60, y: 74, isShow: true, name: "동구" },
    3: { x: 59, y: 75, isShow: true, name: "북구" },
    4: { x: 59, y: 74, isShow: true, name: "서구" },
  },
  // 울산
  "07": {
    0: { x: 102, y: 84, isShow: true, name: "남구" },
    1: { x: 104, y: 83, isShow: true, name: "동구" },
    2: { x: 103, y: 85, isShow: true, name: "북구" },
    3: { x: 101, y: 84, isShow: true, name: "울주군" },
    4: { x: 102, y: 84, isShow: true, name: "중구" },
  },
  // 세종
  "08": {
    0: { x: 65, y: 104, isShow: true, name: "고운동" },
    1: { x: 65, y: 103, isShow: true, name: "금남면" },
    2: { x: 66, y: 103, isShow: true, name: "보람동" },
    3: { x: 66, y: 103, isShow: true, name: "보람동" },
    4: { x: 66, y: 103, isShow: true, name: "보람동" },
    5: { x: 65, y: 104, isShow: true, name: "도담동" },
    6: { x: 67, y: 104, isShow: true, name: "부강면" },
    7: { x: 65, y: 103, isShow: true, name: "새롬동" },
    8: { x: 63, y: 108, isShow: true, name: "소정면" },
    9: { x: 65, y: 104, isShow: true, name: "아름동" },
    10: { x: 65, y: 105, isShow: true, name: "연기면" },
    11: { x: 66, y: 105, isShow: true, name: "연동면" },
    12: { x: 65, y: 106, isShow: true, name: "연서면" },
    13: { x: 64, y: 104, isShow: true, name: "장군면" },
    14: { x: 65, y: 107, isShow: true, name: "전동면" },
    15: { x: 64, y: 108, isShow: true, name: "전의면" },
    16: { x: 66, y: 106, isShow: true, name: "조치원읍" },
    17: { x: 65, y: 104, isShow: true, name: "종촌동" },
    18: { x: 65, y: 103, isShow: true, name: "한솔동" },
  },
  // 제주
  "09": {
    0: { x: 52, y: 33, isShow: true, name: "서귀포시" },
    1: { x: 53, y: 38, isShow: true, name: "제주시" },
  },
  // 경기
  10: {
    0: { x: 69, y: 133, isShow: true, name: "가평군" },
    1: { x: 56, y: 129, isShow: true, name: "고양시" },
    2: { x: 60, y: 124, isShow: true, name: "과천시" },
    3: { x: 58, y: 125, isShow: true, name: "광명시" },
    4: { x: 65, y: 123, isShow: true, name: "광주시" },
    5: { x: 62, y: 127, isShow: true, name: "구리시" },
    6: { x: 59, y: 122, isShow: true, name: "군포시" },
    7: { x: 55, y: 128, isShow: true, name: "김포시" },
    8: { x: 64, y: 128, isShow: true, name: "남양주시" },
    9: { x: 61, y: 134, isShow: true, name: "동두천시" },
    10: { x: 56, y: 125, isShow: true, name: "부천시" },
    11: { x: 63, y: 124, isShow: true, name: "성남시" },
    12: { x: 61, y: 120, isShow: true, name: "수원시" },
    13: { x: 57, y: 123, isShow: true, name: "시흥시" },
    14: { x: 57, y: 121, isShow: true, name: "안산시" },
    15: { x: 57, y: 121, isShow: true, name: "안산시" },
    16: { x: 65, y: 115, isShow: true, name: "안성시" },
    17: { x: 59, y: 123, isShow: true, name: "안양시" },
    18: { x: 61, y: 131, isShow: true, name: "양주시" },
    19: { x: 69, y: 125, isShow: true, name: "양평군" },
    20: { x: 71, y: 121, isShow: true, name: "여주시" },
    21: { x: 61, y: 138, isShow: true, name: "연천군" },
    22: { x: 62, y: 118, isShow: true, name: "오산시" },
    23: { x: 62, y: 120, isShow: true, name: "용인시" },
    24: { x: 60, y: 122, isShow: true, name: "의왕시" },
    25: { x: 61, y: 130, isShow: true, name: "의정부시" },
    26: { x: 68, y: 121, isShow: true, name: "이천시" },
    27: { x: 56, y: 131, isShow: true, name: "파주시" },
    28: { x: 62, y: 114, isShow: true, name: "평택시" },
    29: { x: 64, y: 134, isShow: true, name: "포천시" },
    30: { x: 64, y: 126, isShow: true, name: "하남시" },
    31: { x: 57, y: 119, isShow: true, name: "화성시" },
  },
  //강원
  11: {
    0: { x: 92, y: 131, isShow: true, name: "강릉시" },
    1: { x: 85, y: 145, isShow: true, name: "고성군" },
    2: { x: 97, y: 127, isShow: true, name: "동해시" },
    3: { x: 98, y: 125, isShow: true, name: "삼척시" },
    4: { x: 87, y: 141, isShow: true, name: "속초시" },
    5: { x: 77, y: 139, isShow: true, name: "양구군" },
    6: { x: 88, y: 138, isShow: true, name: "양양군" },
    7: { x: 86, y: 119, isShow: true, name: "영월군" },
    8: { x: 76, y: 122, isShow: true, name: "원주시" },
    9: { x: 80, y: 138, isShow: true, name: "인제군" },
    10: { x: 89, y: 123, isShow: true, name: "정선군" },
    11: { x: 65, y: 139, isShow: true, name: "철원군" },
    12: { x: 73, y: 134, isShow: true, name: "춘천시" },
    13: { x: 95, y: 119, isShow: true, name: "태백시" },
    14: { x: 84, y: 123, isShow: true, name: "평창군" },
    15: { x: 75, y: 130, isShow: true, name: "홍천군" },
    16: { x: 72, y: 139, isShow: true, name: "화천군" },
    17: { x: 77, y: 125, isShow: true, name: "횡성군" },
  },
  // 충북
  12: {
    0: { x: 74, y: 111, isShow: true, name: "괴산군" },
    1: { x: 84, y: 115, isShow: true, name: "단양군" },
    2: { x: 73, y: 103, isShow: true, name: "보은군" },
    3: { x: 74, y: 97, isShow: true, name: "영동군" },
    4: { x: 71, y: 99, isShow: true, name: "옥천군" },
    5: { x: 72, y: 113, isShow: true, name: "음성군" },
    6: { x: 81, y: 118, isShow: true, name: "제천시" },
    7: { x: 71, y: 110, isShow: true, name: "증평군" },
    8: { x: 68, y: 111, isShow: true, name: "진천군" },
    9: { x: 69, y: 107, isShow: true, name: "청주시" },
    10: { x: 76, y: 114, isShow: true, name: "충주시" },
  },
  // 충남
  13: {
    0: { x: 65, y: 99, isShow: true, name: "계룡시" },
    1: { x: 63, y: 102, isShow: true, name: "공주시" },
    2: { x: 69, y: 95, isShow: true, name: "금산군" },
    3: { x: 62, y: 97, isShow: true, name: "논산시" },
    4: { x: 54, y: 112, isShow: true, name: "당진시" },
    5: { x: 54, y: 100, isShow: true, name: "보령시" },
    6: { x: 59, y: 99, isShow: true, name: "부여군" },
    7: { x: 51, y: 110, isShow: true, name: "서산시" },
    8: { x: 55, y: 94, isShow: true, name: "서천군" },
    9: { x: 60, y: 110, isShow: true, name: "아산시" },
    10: { x: 58, y: 107, isShow: true, name: "예산군" },
    11: { x: 63, y: 110, isShow: true, name: "천안시" },
    12: { x: 57, y: 103, isShow: true, name: "청양군" },
    13: { x: 48, y: 109, isShow: true, name: "태안군" },
    14: { x: 48, y: 109, isShow: true, name: "태안군" },
    15: { x: 55, y: 106, isShow: true, name: "홍성군" },
  },
  // 전북
  14: {
    0: { x: 56, y: 80, isShow: true, name: "고창군" },
    1: { x: 56, y: 92, isShow: true, name: "군산시" },
    2: { x: 59, y: 88, isShow: true, name: "김제시" },
    3: { x: 68, y: 80, isShow: true, name: "남원시" },
    4: { x: 72, y: 93, isShow: true, name: "무주군" },
    5: { x: 56, y: 87, isShow: true, name: "부안군" },
    6: { x: 63, y: 79, isShow: true, name: "순창군" },
    7: { x: 63, y: 89, isShow: true, name: "완주군" },
    8: { x: 63, y: 89, isShow: true, name: "완주군" },
    9: { x: 60, y: 91, isShow: true, name: "익산시" },
    10: { x: 66, y: 84, isShow: true, name: "임실군" },
    11: { x: 70, y: 85, isShow: true, name: "장수군" },
    12: { x: 63, y: 89, isShow: true, name: "전주시" },
    13: { x: 58, y: 83, isShow: true, name: "정읍시" },
    14: { x: 68, y: 88, isShow: true, name: "진안군" },
  },
  // 전남
  15: {
    0: { x: 73, y: 66, isShow: true, name: "여수시" },
    1: { x: 70, y: 70, isShow: true, name: "순천시" },
    2: { x: 56, y: 71, isShow: true, name: "나주시" },
    3: { x: 73, y: 70, isShow: true, name: "광양시" },
    4: { x: 61, y: 78, isShow: true, name: "담양군" },
    5: { x: 66, y: 77, isShow: true, name: "곡성군" },
    6: { x: 69, y: 75, isShow: true, name: "구례군" },
    7: { x: 66, y: 62, isShow: true, name: "고흥군" },
    8: { x: 62, y: 66, isShow: true, name: "보성군" },
    9: { x: 61, y: 72, isShow: true, name: "화순군" },
    10: { x: 59, y: 64, isShow: true, name: "장흥군" },
    11: { x: 57, y: 63, isShow: true, name: "강진군" },
    12: { x: 54, y: 61, isShow: true, name: "해남군" },
    13: { x: 56, y: 66, isShow: true, name: "영암군" },
    14: { x: 52, y: 71, isShow: true, name: "무안군" },
    15: { x: 52, y: 72, isShow: true, name: "함평군" },
    16: { x: 52, y: 77, isShow: true, name: "영광군" },
    17: { x: 57, y: 56, isShow: true, name: "완도군" },
    18: { x: 48, y: 59, isShow: true, name: "진도군" },
    19: { x: 50, y: 66, isShow: true, name: "신안군" },
    20: { x: 50, y: 67, isShow: true, name: "목포시" },
  },
  // 경북
  16: {
    0: { x: 91, y: 90, isShow: true, name: "경산시" },
    1: { x: 100, y: 91, isShow: true, name: "경주시" },
    2: { x: 83, y: 87, isShow: true, name: "고령군" },
    3: { x: 84, y: 96, isShow: true, name: "구미시" },
    4: { x: 88, y: 99, isShow: true, name: "군위군" },
    5: { x: 80, y: 96, isShow: true, name: "김천시" },
    6: { x: 81, y: 106, isShow: true, name: "문경시" },
    7: { x: 90, y: 113, isShow: true, name: "봉화군" },
    8: { x: 81, y: 102, isShow: true, name: "상주시" },
    9: { x: 83, y: 91, isShow: true, name: "성주군" },
    10: { x: 91, y: 106, isShow: true, name: "안동시" },
    11: { x: 102, y: 103, isShow: true, name: "영덕군" },
    12: { x: 97, y: 108, isShow: true, name: "영양군" },
    13: { x: 89, y: 111, isShow: true, name: "영주시" },
    14: { x: 95, y: 93, isShow: true, name: "영천시" },
    15: { x: 86, y: 107, isShow: true, name: "예천군" },
    16: { x: 102, y: 115, isShow: true, name: "울진군" },
    17: { x: 90, y: 101, isShow: true, name: "의성군" },
    18: { x: 91, y: 86, isShow: true, name: "청도군" },
    19: { x: 96, y: 103, isShow: true, name: "청송군" },
    20: { x: 85, y: 93, isShow: true, name: "칠곡군" },
    21: { x: 102, y: 95, isShow: true, name: "포항시" },
  },
  // 경남
  17: {
    0: { x: 90, y: 69, isShow: true, name: "거제시" },
    1: { x: 77, y: 86, isShow: true, name: "거창군" },
    2: { x: 85, y: 71, isShow: true, name: "고성군" },
    3: { x: 95, y: 77, isShow: true, name: "김해시" },
    4: { x: 77, y: 68, isShow: true, name: "남해군" },
    5: { x: 92, y: 83, isShow: true, name: "밀양시" },
    6: { x: 80, y: 71, isShow: true, name: "사천시" },
    7: { x: 76, y: 80, isShow: true, name: "산청군" },
    8: { x: 97, y: 79, isShow: true, name: "양산시" },
    9: { x: 83, y: 78, isShow: true, name: "의령군" },
    10: { x: 81, y: 75, isShow: true, name: "진주시" },
    11: { x: 87, y: 83, isShow: true, name: "창녕군" },
    12: { x: 89, y: 76, isShow: true, name: "창원시" },
    13: { x: 87, y: 68, isShow: true, name: "통영시" },
    14: { x: 74, y: 73, isShow: true, name: "하동군" },
    15: { x: 86, y: 77, isShow: true, name: "함안군" },
    16: { x: 74, y: 82, isShow: true, name: "함양군" },
    17: { x: 81, y: 84, isShow: true, name: "합천군" },
  },
};

// export const area = [
//   "서울특별시 강남구",
//   "서울특별시 강동구",
//   "서울특별시 강북구",
//   "서울특별시 강서구",
//   "서울특별시 관악구",
//   "서울특별시 광진구",
//   "서울특별시 구로구",
//   "서울특별시 금천구",
//   "서울특별시 노원구",
//   "서울특별시 도봉구",
//   "서울특별시 동대문구",
//   "서울특별시 동작구",
//   "서울특별시 마포구",
//   "서울특별시 서대문구",
//   "서울특별시 서초구",
//   "서울특별시 성동구",
//   "서울특별시 성북구",
//   "서울특별시 송파구",
//   "서울특별시 양천구",
//   "서울특별시 영등포구",
//   "서울특별시 용산구",
//   "서울특별시 은평구",
//   "서울특별시 종로구",
//   "서울특별시 중구",
//   "서울특별시 중랑구",
//   "경기도 수원시",
//   "경기도 성남시",
//   "경기도 의정부시",
//   "경기도 안양시",
//   "경기도 부천시",
//   "경기도 광명시",
//   "경기도 평택시",
//   "경기도 동두천시",
//   "경기도 안산시",
//   "경기도 고양시",
//   "경기도 과천시",
//   "경기도 구리시",
//   "경기도 남양주시",
//   "경기도 오산시",
//   "경기도 시흥시",
//   "경기도 군포시",
//   "경기도 의왕시",
//   "경기도 하남시",
//   "경기도 용인시",
//   "경기도 파주시",
//   "경기도 이천시",
//   "경기도 안성시",
//   "경기도 김포시",
//   "경기도 화성시",
//   "경기도 광주시",
//   "경기도 양주시",
//   "경기도 포천시",
//   "경기도 여주시",
//   "경기도 연천군",
//   "경기도 가평군",
//   "경기도 양평군",
//   "인천광역시 계양구",
//   "인천광역시 미추홀구",
//   "인천광역시 남동구",
//   "인천광역시 동구",
//   "인천광역시 부평구",
//   "인천광역시 서구",
//   "인천광역시 연수구",
//   "인천광역시 중구",
//   "인천광역시 강화군",
//   "인천광역시 옹진군",
//   "강원도 춘천시",
//   "강원도 원주시",
//   "강원도 강릉시",
//   "강원도 동해시",
//   "강원도 태백시",
//   "강원도 속초시",
//   "강원도 삼척시",
//   "강원도 홍천군",
//   "강원도 횡성군",
//   "강원도 영월군",
//   "강원도 평창군",
//   "강원도 정선군",
//   "강원도 철원군",
//   "강원도 화천군",
//   "강원도 양구군",
//   "강원도 인제군",
//   "강원도 고성군",
//   "강원도 양양군",
//   "충청북도 청주시",
//   "충청북도 충주시",
//   "충청북도 제천시",
//   "충청북도 보은군",
//   "충청북도 옥천군",
//   "충청북도 영동군",
//   "충청북도 증평군",
//   "충청북도 진천군",
//   "충청북도 괴산군",
//   "충청북도 음성군",
//   "충청북도 단양군",
//   "충청남도 천안시",
//   "충청남도 공주시",
//   "충청남도 보령시",
//   "충청남도 아산시",
//   "충청남도 서산시",
//   "충청남도 논산시",
//   "충청남도 계룡시",
//   "충청남도 당진시",
//   "충청남도 금산군",
//   "충청남도 부여군",
//   "충청남도 서천군",
//   "충청남도 청양군",
//   "충청남도 홍성군",
//   "충청남도 예산군",
//   "충청남도 태안군",
//   "대전광역시 대덕구",
//   "대전광역시 동구",
//   "대전광역시 서구",
//   "대전광역시 유성구",
//   "대전광역시 중구",
//   "전라북도 전주시",
//   "전라북도 군산시",
//   "전라북도 익산시",
//   "전라북도 정읍시",
//   "전라북도 남원시",
//   "전라북도 김제시",
//   "전라북도 완주군",
//   "전라북도 진안군",
//   "전라북도 무주군",
//   "전라북도 장수군",
//   "전라북도 임실군",
//   "전라북도 순창군",
//   "전라북도 고창군",
//   "전라북도 부안군",
//   "전라남도 목포시",
//   "전라남도 여수시",
//   "전라남도 순천시",
//   "전라남도 나주시",
//   "전라남도 광양시",
//   "전라남도 담양군",
//   "전라남도 곡성군",
//   "전라남도 구례군",
//   "전라남도 고흥군",
//   "전라남도 보성군",
//   "전라남도 화순군",
//   "전라남도 장흥군",
//   "전라남도 강진군",
//   "전라남도 해남군",
//   "전라남도 영암군",
//   "전라남도 무안군",
//   "전라남도 함평군",
//   "전라남도 영광군",
//   "전라남도 장성군",
//   "전라남도 완도군",
//   "전라남도 진도군",
//   "전라남도 신안군",
//   "광주광역시 광산구",
//   "광주광역시 남구",
//   "광주광역시 동구",
//   "광주광역시 북구",
//   "광주광역시 서구",
//   "경상북도 포항시",
//   "경상북도 경주시",
//   "경상북도 김천시",
//   "경상북도 안동시",
//   "경상북도 구미시",
//   "경상북도 영주시",
//   "경상북도 영천시",
//   "경상북도 상주시",
//   "경상북도 문경시",
//   "경상북도 경산시",
//   "경상북도 군위군",
//   "경상북도 의성군",
//   "경상북도 청송군",
//   "경상북도 영양군",
//   "경상북도 영덕군",
//   "경상북도 청도군",
//   "경상북도 고령군",
//   "경상북도 성주군",
//   "경상북도 칠곡군",
//   "경상북도 예천군",
//   "경상북도 봉화군",
//   "경상북도 울진군",
//   "경상남도 창원시",
//   "경상남도 진주시",
//   "경상남도 통영시",
//   "경상남도 사천시",
//   "경상남도 김해시",
//   "경상남도 밀양시",
//   "경상남도 거제시",
//   "경상남도 양산시",
//   "경상남도 의령군",
//   "경상남도 함안군",
//   "경상남도 창녕군",
//   "경상남도 고성군",
//   "경상남도 남해군",
//   "경상남도 하동군",
//   "경상남도 산청군",
//   "경상남도 함양군",
//   "경상남도 거창군",
//   "경상남도 합천군",
//   "부산광역시 강서구",
//   "부산광역시 금정구",
//   "부산광역시 남구",
//   "부산광역시 동구",
//   "부산광역시 동래구",
//   "부산광역시 부산진구",
//   "부산광역시 북구",
//   "부산광역시 사상구",
//   "부산광역시 사하구",
//   "부산광역시 서구",
//   "부산광역시 수영구",
//   "부산광역시 연제구",
//   "부산광역시 영도구",
//   "부산광역시 중구",
//   "부산광역시 해운대구",
//   "부산광역시 기장군",
//   "대구광역시 남구",
//   "대구광역시 달서구",
//   "대구광역시 동구",
//   "대구광역시 북구",
//   "대구광역시 서구",
//   "대구광역시 수성구",
//   "대구광역시 중구",
//   "대구광역시 달성군",
//   "울산광역시 남구",
//   "울산광역시 동구",
//   "울산광역시 북구",
//   "울산광역시 중구",
//   "울산광역시 울주군",
//   "제주도 서귀포시",
//   "제주도 제주시",
//   "세종시 소정면",
//   "세종시 전의면",
//   "세종시 전동면",
//   "세종시 연서면",
//   "세종시 조치원읍",
//   "세종시 장군면",
//   "세종시 연기면",
//   "세종시 연동면",
//   "세종시 부강면",
//   "세종시 금남면",
//   "세종시 보람동",
//   "세종시 고운동",
//   "세종시 아름동",
//   "세종시 도담동",
//   "세종시 종촌동",
//   "세종시 새롬동",
//   "세종시 한솔동",
// ];
